/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Wislls Lima
 */
public class CadastrarPage1 extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public CadastrarPage1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTelefone = new javax.swing.JLabel();
        TextTelefoneCad = new javax.swing.JTextField();
        NascimentoCad = new javax.swing.JFormattedTextField();
        LabelNascimentoCad = new javax.swing.JLabel();
        LabelSobrenomeCad = new javax.swing.JLabel();
        TextUsuario2 = new javax.swing.JTextField();
        ProximaTelaCad = new javax.swing.JButton();
        TextNomeCad = new javax.swing.JTextField();
        LabelNomeCad = new javax.swing.JLabel();
        LabelCadastrarCad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        LabelTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTelefone.setText("Telefone");
        getContentPane().add(LabelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, 80, 50));

        TextTelefoneCad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextTelefoneCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefoneCadActionPerformed(evt);
            }
        });
        getContentPane().add(TextTelefoneCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 280, 40));

        NascimentoCad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NascimentoCad.setAlignmentX(0.0F);
        NascimentoCad.setAlignmentY(0.0F);
        NascimentoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NascimentoCadActionPerformed(evt);
            }
        });
        getContentPane().add(NascimentoCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 280, 40));

        LabelNascimentoCad.setForeground(new java.awt.Color(255, 255, 255));
        LabelNascimentoCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNascimentoCad.setText("Data Nascimento");
        getContentPane().add(LabelNascimentoCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 100, 50));

        LabelSobrenomeCad.setForeground(new java.awt.Color(255, 255, 255));
        LabelSobrenomeCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSobrenomeCad.setText("Sobrenome");
        getContentPane().add(LabelSobrenomeCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 80, 50));

        TextUsuario2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextUsuario2.setAlignmentX(0.0F);
        TextUsuario2.setAlignmentY(0.0F);
        TextUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuario2ActionPerformed(evt);
            }
        });
        getContentPane().add(TextUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 280, 40));

        ProximaTelaCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProximaTelaCad.setText("Próximo");
        ProximaTelaCad.setAlignmentY(0.0F);
        ProximaTelaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximaTelaCadActionPerformed(evt);
            }
        });
        getContentPane().add(ProximaTelaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 690, 160, 50));

        TextNomeCad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextNomeCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeCadActionPerformed(evt);
            }
        });
        getContentPane().add(TextNomeCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 280, 40));

        LabelNomeCad.setForeground(new java.awt.Color(255, 255, 255));
        LabelNomeCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomeCad.setText("Nome");
        getContentPane().add(LabelNomeCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 120, 50));

        LabelCadastrarCad.setFont(new java.awt.Font("Segoe Print", 0, 48)); // NOI18N
        LabelCadastrarCad.setForeground(new java.awt.Color(255, 255, 255));
        LabelCadastrarCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelCadastrarCad.setText("Cadastrar");
        getContentPane().add(LabelCadastrarCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 280, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/painel-login.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 580, 480));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Logo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomeCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeCadActionPerformed

    private void ProximaTelaCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximaTelaCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProximaTelaCadActionPerformed

    private void TextUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuario2ActionPerformed

    private void NascimentoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NascimentoCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NascimentoCadActionPerformed

    private void TextTelefoneCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefoneCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefoneCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCadastrarCad;
    private javax.swing.JLabel LabelNascimentoCad;
    private javax.swing.JLabel LabelNomeCad;
    private javax.swing.JLabel LabelSobrenomeCad;
    private javax.swing.JLabel LabelTelefone;
    private javax.swing.JFormattedTextField NascimentoCad;
    private javax.swing.JButton ProximaTelaCad;
    private javax.swing.JTextField TextNomeCad;
    private javax.swing.JTextField TextTelefoneCad;
    private javax.swing.JTextField TextUsuario2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFundo;
    // End of variables declaration//GEN-END:variables
}
